version: '3.5'

services:

  db-server:
    image: postgres:latest
    container_name: postgres-db-server
    hostname: postgres-db-server
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Aa12345!!
      - POSTGRES_DB=cheko
      - PGPORT=5432
    ports:
      - "5432:5432"

  redis-server:
    image: redis:7-alpine
    container_name: redis-server
    hostname: redis-server
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]